name: Run TMDB person query

on:
  workflow_dispatch:
    inputs:
      person:
        description: 'Person to query'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run query
        run: |
            python tmdbquery.py --api_key ${{ secrets.TMDB_API_KEY }} --person "${{ github.event.inputs.person }}" --md >> $GITHUB_STEP_SUMMARY
