name: Run TMDB query

on:
  workflow_dispatch:
    inputs:
      movie:
        description: 'Movie to query'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up Python 3.12
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run query
        run: |
            python tmdbquery.py --api_key ${{ secrets.TMDB_API_KEY }} --movie ${{ github.event.inputs.movie}}
